### ISSUE TITLE
RTL issue on Safari and Mobile browsers

### ISSUE THREAD

**Issue by jrbgarcia29** [creativetimofficial/vue-black-dashboard#1]
Hi, I noticed an issue on Safari and mobile. We can replicate the issue on the live demo page: after clicking the RTL support link, then going back to dashboard, the display is destroyed, i.e some text didn't returned properly from RTL, the scrollbar also stayed at the left side, instead of going back to the right. Please help me how to handle this is there's a solution for it.

<img width="1294" alt="screen shot 2019-03-01 at 9 33 37 pm" src="https://user-images.githubusercontent.com/7112826/53642641-38968080-3c6d-11e9-9578-f9b23d754404.png">

**Comment by Craig-Burch** [comment]
@jrbgarcia29 This RTL plugin is giving me a headache as well, I am going to work on deleting it entirely from the app. If that is something you are looking to do as well I will let you know once I am done.

**Comment by Craig-Burch** [comment]
@jrbgarcia29 adding this to my local css file seems to be the quick fix.

/*get rid of RTL by forcing Left to Right content*/
body {
  direction: ltr !important;
}

I needed to disable the RTL entirely but based on your question you may be wanting it to stay enabled and transition back and forth without the current bug we are all dealing with for safari browsers.
If that is the case then I am unsure on where to start with that. ONE thing I did do in App.vue was this:

 mounted() {
      // comment below ensures new css add on works
      //by forcing the app to run RTL perpetually 
      // this.$watch('$route', this.disableRTL, { immediate: true });
      this.$watch('$sidebar.showSidebar', this.toggleNavOpen)
    }

It was mainly for probing but commenting out this line allowed me to have the bug enabled perpetually on my windows computer so I could debug. The css given is what finally allowed the bug to be overridden even with the rtl enabled since i commented out this line that disables it.

**Comment by guenoledc** [comment]
Hi,

I encountered the same problem: on mobile the orientation was not respected and I cannot fully explain the rational, except that I believe that the direction property of the text is not initialised in the same way on mobile than on PC.
Because I lost approx half a day, I spend 30 min to document ...

Anyway, i dug into the implementation of the RTLPlugin and found a number of point that I corrected
* first, the `disableRTL()` method of the `app.vue` was testing if `this.$rtl.isRTL` was `false` to disable RTL. This looks to be the otherway around. So here is the correction
```js
    disableRTL() {
      if (this.$rtl.isRTL) {
       this.$rtl.disableRTL();
      }
    },
```
* Then the `isRTL` property of the plugin was initialized to false which makes sense, but then did not trigger the `disableRTL`. So I preferred a computed property for `isRTL` that depends on the state of the class in the body as follow
```js
        isRTL() {
          this.forceRTLRecompute; // this is explained below
          return this.getDocClasses().contains("rtl") || this.getDocClasses().contains("menu-on-right")
        }
```
But since the computed property depends on the DOM and not on the content of a property, it does not get recomputed. Sic ! So I tricked with a fake variable `forceRTLRecompute`. The plugin looks like this now:
```js
export default {
  install(Vue) {
    let app = new Vue({
      data() {
        console.log("RTLPlugin", "data()")
        return {
          forceRTLRecompute: false,
        }
      },
      methods: {
        getDocClasses() {
          return document.body.classList
        },
        enableRTL() {
          this.getDocClasses().add('rtl');
          this.getDocClasses().add('menu-on-right');
          this.toggleBootstrapRTL(true);
          this.forceRTLRecompute = true // to force recomputing
        },
        disableRTL() {
          this.getDocClasses().remove('rtl');
          this.getDocClasses().remove('menu-on-right');
          this.toggleBootstrapRTL(false);
          this.forceRTLRecompute = false // to force recomputing
        },
        toggleBootstrapRTL(value) {
          for (let i=0; i < document.styleSheets.length; i++){
            let styleSheet = document.styleSheets[i];
            let { href } = styleSheet;
            if(href && href.endsWith('bootstrap-rtl.css')){
              styleSheet.disabled = !value;
            }
          }
        }
      },
      computed: {
        isRTL() {
          this.forceRTLRecompute; // to create a dependancy on the property
          return this.getDocClasses().contains("rtl") || this.getDocClasses().contains("menu-on-right")
        }
      }
    });
    Vue.prototype.$rtl = app;
  }
}

```

* Then, I had to change the `_rtl.scss` because i could not find a place where the direction of the text was set according to the RTL value. 
```css
// added at the top of the file
body {
  direction: ltr;
}
body.rtl {
  direction: rtl;
}

```

Now it seems to work.
